variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build

default:
  image: crops/poky
  tags: 
    - linux

before_script:
  - echo "$PRIVATE_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519
  - echo "$PUBLIC_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519.pub
  - mkdir -p layers/meta-estalor-distro/recipes-connectivity/wpa-supplicant/files/estalor
  - echo "$WIFI_KEY" > layers/meta-estalor-distro/recipes-connectivity/wpa-supplicant/files/estalor/wpa_supplicant-nl80211-wlan0.conf
  - TEMPLATECONF=${PWD}/layers/meta-estalor/conf/templates/estalor . sources/poky/oe-init-build-env

Test-Homeassistant-Arm64-A72:
  stage: build
  script:
    - MACHINE=qemuarm64-a72 bitbake core-image-homeassistant

# Test-Homeassistant-X86-64:
#   stage: build
#   script:
#     - MACHINE=qemux86-64 bitbake core-image-homeassistant

# Test-Reterminal-Qemu:
#   stage: build
#   script:
#     - MACHINE=qemuarm64-a72 bitbake estalor-qemuarm64-bundle-debug estalor-image-debug

# Test-Reterminal-Aarch64:
#   stage: build
#   script:
#     - bitbake estalor-image-debug estalor-reterminal-bundle-debug