name: Gitea Actions Yocto Project
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  Build-HomeAssistant-Arm64:
    runs-on: yocto-builder
    container:
      volumes:
          - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLICKEY: ${{ secrets.PUBLIC_KEY }}
          WIFI_KEY: ${{ secrets.WIFI_KEY }}
      - name: Build QemuArm64-A72 Core Image Homeassistant
        run: |
          echo "$PRIVATE_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519
          echo "$PUBLIC_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519.pub
          mkdir -p ${{ gitea.workspace }}/layers/meta-estalor/recipes-connectivity/wpa-supplicant/files/estalor
          echo "$WIFI_KEY" > layers/meta-estalor/recipes-connectivity/wpa-supplicant/files/estalor/wpa_supplicant-nl80211-wlan0.conf
          TEMPLATECONF=${{ gitea.workspace }}/layers/meta-estalor/conf/templates/estalor . ${{ gitea.workspace }}/sources/poky/oe-init-build-env
          MACHINE=qemuarm64-a72 bitbake core-image-homeassistant-full

  Build-HomeAssistant-X86-64:
    runs-on: yocto-builder
    container:
      volumes:
          - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLICKEY: ${{ secrets.PUBLIC_KEY }}
          WIFI_KEY: ${{ secrets.WIFI_KEY }}
      - name: Build QemuX86-64 Core Image Homeassistant
        run: |
          echo "$PRIVATE_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519
          echo "$PUBLIC_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519.pub
          mkdir -p ${{ gitea.workspace }}/layers/meta-estalor/recipes-connectivity/wpa-supplicant/files/estalor
          echo "$WIFI_KEY" > layers/meta-estalor/recipes-connectivity/wpa-supplicant/files/estalor/wpa_supplicant-nl80211-wlan0.conf
          TEMPLATECONF=${{ gitea.workspace }}/layers/meta-estalor/conf/templates/estalor . ${{ gitea.workspace }}/sources/poky/oe-init-build-env
          MACHINE=qemux86-64 bitbake core-image-homeassistant-full

  Build-Reterminal-Qemu:
    runs-on: yocto-builder
    container:
      volumes:
          - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLICKEY: ${{ secrets.PUBLIC_KEY }}
          WIFI_KEY: ${{ secrets.WIFI_KEY }}
      - name: Build QemuArm64-A72 Reterminal Image
        run: |
          echo "$PRIVATE_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519
          echo "$PUBLIC_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519.pub
          mkdir -p ${{ gitea.workspace }}/layers/meta-estalor/recipes-connectivity/wpa-supplicant/files/estalor
          echo "$WIFI_KEY" > layers/meta-estalor/recipes-connectivity/wpa-supplicant/files/estalor/wpa_supplicant-nl80211-wlan0.conf
          TEMPLATECONF=${{ gitea.workspace }}/layers/meta-estalor/conf/templates/estalor . ${{ gitea.workspace }}/sources/poky/oe-init-build-env
          MACHINE=qemuarm64-a72 bitbake estalor-qemuarm64-bundle-debug

  Build-Reterminal-Arm64-A72:
    runs-on: yocto-builder
    container:
      volumes:
          - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLICKEY: ${{ secrets.PUBLIC_KEY }}
          WIFI_KEY: ${{ secrets.WIFI_KEY }}
      - name: Build Arm64-A72 Reterminal Image
        run: |
          echo "$PRIVATE_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519
          echo "$PUBLIC_KEY" > layers/meta-estalor/recipes-connectivity/openssh/openssh/id_ed25519.pub
          mkdir -p ${{ gitea.workspace }}/layers/meta-estalor/recipes-connectivity/wpa-supplicant/files/estalor
          echo "$WIFI_KEY" > layers/meta-estalor/recipes-connectivity/wpa-supplicant/files/estalor/wpa_supplicant-nl80211-wlan0.conf
          TEMPLATECONF=${{ gitea.workspace }}/layers/meta-estalor/conf/templates/estalor . ${{ gitea.workspace }}/sources/poky/oe-init-build-env
          bitbake estalor-reterminal-bundle-debug
      # - name: Upload Artifacts
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: Reterminal
      #     path: |
      #       ${{ gitea.workspace }}/build/tmp/deploy/images/reterminal/estalor-reterminal-bundle-debug.raucb
      #       ${{ gitea.workspace }}/build/tmp/deploy/images/reterminal/estalor-image-debug-reterminal.wic.bmap
      #       ${{ gitea.workspace }}/build/tmp/deploy/images/reterminal/estalor-image-debug-reterminal.wic.bz2

  Clean-Up-Cache:
    runs-on: yocto-builder
    container:
      volumes:
        - /cache/:/cache/
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          submodules: true
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PUBLICKEY: ${{ secrets.PUBLIC_KEY }}
          WIFI_KEY: ${{ secrets.WIFI_KEY }}
      - name: Clean SState Cache
        run: |
          python3 ${{ gitea.workspace }}/sources/poky/scripts/sstate-cache-management.py --cache-dir=/cache/sstate -y -d -v